version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
    ports:
      # - 5173:5173
      - 5174:5174
      - 5175:5175


  web:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: infra/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netview
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d:cached
    ports:
      - 3306:3306

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8081:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
        
volumes:
  db-store: